### ISSUE TITLE
Issue importing with Rollup

### ISSUE THREAD

**Issue by andrewmclagan** [ylletjs/yllet#27]
### What I expected

Ability to bundle this package with rollup within another package.

### What happened instead

Multiple errors with `fs` package (browser?) relating to `form-data` package.

Is this package isomorphic?

### Steps to reproduce

```javascript
import babel from "rollup-plugin-babel";
import json from "rollup-plugin-json";
import commonjs from "rollup-plugin-commonjs";
import includePaths from "rollup-plugin-includepaths";
import external from "rollup-plugin-peer-deps-external";
import builtins from "rollup-plugin-node-builtins";
import resolve from "rollup-plugin-node-resolve";

export default {
  input: "src/index.js",
  output: [
    {
      file: "dist/index.js",
      format: "cjs",
      sourcemap: true
    },
    {
      file: "dist/index.es.js",
      format: "es",
      sourcemap: true
    }
  ],
  plugins: [
    external(),
    builtins(),
    babel({
      exclude: /node_modules/,
      rootMode: "upward"
    }),
    json(),
    includePaths({
      paths: ["src"]
    }),
    resolve({ preferBuiltins: false }),
    commonjs()
  ]
};

```

**Comment by frozzare** [comment]
Hm, I'm not sure how to exactly reproduce this since you only gave my the configuration file and not all the parts.

What I did with your configuration file was this:
1. Install everything
2. Create `rollup.config.js` with your configuration
3. Create `src/index.js` and add some code [1]
4. Run ` rollup --config` without any problems.

This package should without any problems when building web apps with a bundle tool like webpack or rollup. You can checkout the demo projects using react https://github.com/ylletjs/demo-react

[1]
```
const Client = require('yllet');

const client = new Client({
    endpoint: 'https://cors-anywhere.herokuapp.com/https://demo.wp-api.org/wp-json/',
    headers: {
        'X-Requested-With': 'Yllet'
    }
});

client.posts().get()
    .then(res => {
        res.data.forEach(p => {
          document.getElementById("app").innerHTML += '<li>' + p.title.rendered + '</li>';
        })
    });
```

**Comment by andrewmclagan** [comment]
Yes, sorry for not being clear. 

The specific error we receive is:

```javascript
# Function.useColors
# ./Users/[redacted]/web/packages/sdk/dist/index.es.js:1609
function useColors() {
  return 'colors' in exports.inspectOpts
    ? Boolean(exports.inspectOpts.colors)
    : tty.isatty(process.stderr.fd);
}
```

This looks like some kind of shim injected by `rollup-plugin-node-builtins` to support node features in the browser? So we disabled this plugin. Although we get another error:

```
Module not found: Can't resolve 'fs'
```

This is the reason we used `rollup-plugin-node-builtins` in the first place... Also with `rollup-plugin-node-resolve` and with `{ preferBuiltins: true }` set or even `{ preferBuiltins: false }` set we receive the same error 

```
Module not found: Can't resolve 'fs'
```

My thoughts are its something to do with `axios`? As this library makes no specific reference to any node only imports. Although axios is supposedly node compatible... Therefore I think its a Rollup + axios issue?

-------------

P.S. Great library we are migrating from `wpapi` as its pretty bloated. We were thinking of creating a fork of `yllet` that abstracts the transport layer so we can use `fetch` instead and others could still use `axios` if they wanted.

**Comment by andrewmclagan** [comment]
Question: Is this library exporting `ES6` code OR `CJS`? This could be the issue... as most bundlers assume external modules are not needing transpiling

**Comment by frozzare** [comment]
I'm not sure if it's a error with rollup or axios, I have never used rollup so I can't say anything about it. 

But I don't think it's a error with this package since my simple test worked with rollup as you can read in my previous post.

This package is exporting `ES5` code with `require` and `exports.__esModule = true;` and that worked with rollup when I tested.

**Comment by andrewmclagan** [comment]
Ah ok, yes looking at the dist code as you mentioned:

```javascript
exports.__esModule = true;
```

That is actually es6 code.
